linuxfoundation/insights

- frontend/app/config/benchmarks/configs/active-days.ts
This PR fixes a typo in one of the Health Score benchmarks in the Project's Overview page.
Previously we had "Active Days Benchmarks" which is not consistent with the remaining metrics that do not have the "Benchmarks" suffix. This PR removes the "Benchmarks" from the copy.
> fix: benchmarks copy

- frontend/app/components/modules/project/services/security.service.ts
- frontend/app/components/modules/project/views/overview.vue
- frontend/app/components/modules/project/views/security.vue
- Added function to hide documentation and vulnerability management categories from the security score
- Applied the filter to both the overview and security and best practices tab
[INS-639](https://linear.app/lfx/issue/INS-639/hide-documentation-and-vulnerability-management-metrics-for-now)
> added function that temporarily hides documentation and vulnerability

- frontend/app/config/menu/index.ts
This PR enables the Menu link for the Open Source Index page.
> chore: enable oss index menu link

- frontend/app/components/modules/open-source-index/components/osi-header.vue
- Remove the "breadcrumb" links from the OSS Index page header
- Adjusted the font weight to match design
[INS-611](https://linear.app/lfx/issue/INS-611/confirm-breadcrumb-hover-with-nuno)
> remove breadcrumb links

- frontend/app/components/shared/modules/share/components/active-contributor-badge.vue
- frontend/app/components/shared/modules/share/components/share-badge.vue
Remove the query parameters from the share badge - copy markdown feature
[INS-662](https://linear.app/lfx/issue/INS-662/remove-query-params-from-badge-link)
> bugfix: remove share badge query parameters

- frontend/app/components/modules/project/config/trust-score.ts
Changed the typo in the trust-score config for the "stable" score
[INS-664](https://linear.app/lfx/issue/INS-664/stable-renders-weirdly)
> fix typo config color

- frontend/app/components/modules/widget/components/shared/widget-area.vue
- frontend/app/components/modules/widget/config/popularity/search-queries/search-queries.config.ts
- frontend/app/components/modules/widget/config/popularity/search-queries/search-queries.vue
- frontend/app/components/modules/widget/config/widget-area.config.ts
- frontend/app/components/modules/widget/config/widget.config.ts
- Changed widget title and description
- Added hideOnRepoFilter flag for widgets that hides them when the repository is filtered
- Fixed the chart's granularity to monthly
- Show empty data if the date filter is below 30 days
[INS-676](https://linear.app/lfx/issue/INS-676/update-the-frontend-code-for-the-search-queries-widget-to-match-the)
> search query widget adjustments

- frontend/app/components/modules/explore/components/top-contributors.vue
- frontend/app/components/modules/explore/components/top-organizations.vue
- frontend/app/components/modules/explore/config/top-section-tabs.ts
- Removed the contributions value from the top contributors and organization and made it only visible on the view more
- Removed the word "active" from the title
- Description changes for top contributors and organization components
[INS-678](https://linear.app/lfx/issue/INS-678/changes-to-leaderboards-on-explore-page)
> explore page top section text changes and column display

- frontend/app/components/modules/project/views/overview.vue
Removed the extra paddings on the overview page that causes it to go out of bounds of the container
[INS-703](https://linear.app/lfx/issue/INS-703/overview-page-goes-out-of-container-bounds)
> fix: overview page paddings

- frontend/app/pages/project/[slug].vue
Set the time range and dates to default whenever the user changes project selection
[INS-624](https://linear.app/lfx/issue/INS-624/filters-should-not-persists-across-projects)
> fix: reset selected time filters when the user changes project

- frontend/server/data/tinybird/search-queries-data-source.ts
This depends on having changed the date format returned from TinyBird, so it doesn't include time, just the date.
> fix: fix the start and end dates format for the search volume data source

- frontend/app/components/modules/explore/config/top-section-tabs.ts
- frontend/app/components/modules/explore/services/explore.api.service.ts
- Changed the description of the top projects list in the explore page
- Changed the sorting "contributorCount_desc" to match the description
[INS-714](https://linear.app/lfx/issue/INS-714/change-the-description-and-sorting-of-top-projects-in-the-leaderboard)
> feat: changed the sorting and description of the top projects list

- frontend/app/components/shared/types/granularity.ts
Changed the label format for the X Axis on charts that are in quarterly granularity to display Q{quarter number} {yyyy}
[INS-666](https://linear.app/lfx/issue/INS-666/date-labels-are-set-as-days-if-you-select-quarterly-they-should-be-q1)
> feat:changed granularity format for quarterly charts

- frontend/app/components/modules/collection/views/collection-details.vue
- frontend/app/components/modules/collection/views/collection-list.vue
- frontend/app/components/modules/project/components/shared/header/date-range-picker.vue
- frontend/app/components/shared/utils/query-param.ts
- Changed the way the URL params are stored by using router.push instead of replace, this enables the browser to store the filter changes and be able to use the back or forward button
- Applied the changes to the projects page and on the collections list page
[INS-631](https://linear.app/lfx/issue/INS-631/url-history-doesnt-seem-to-be-used-when-changing-the-date-range)
> fix: url parameter history

- frontend/app/components/modules/widget/config/contributor/active-contributors/active-contributors.vue
- frontend/app/components/modules/widget/config/contributor/active-organizations/active-organizations.vue
- frontend/app/components/uikit/chart/helpers/chart-helpers.ts
- frontend/pnpm-lock.yaml
- Fix bug on the active contributors and orgs granularity tab not setting correctly for All Time
- Removed the empty or 0 rows from the data on those 2 widgets when the user selects All Time
[INS-722](https://linear.app/lfx/issue/INS-722/dont-show-empty-bars-for-alltime)
> fix: active org and contributor chart display for all time

- frontend/app/components/modules/widget/config/popularity/search-queries/search-queries.vue
Added the "Data available from June 2024 onward" message below the chart on the search queries widget
[INS-733](https://linear.app/lfx/issue/INS-733/improve-search-volume-widget-description)
> feat: added data availability status on search queries widget

- frontend/app/components/modules/widget/config/popularity/package-dependency/fragments/package-legend-item.vue
- frontend/app/components/modules/widget/config/popularity/package-dependency/package-dependency.config.ts
- frontend/app/components/modules/widget/config/popularity/package-dependency/package-dependency.vue
- frontend/app/components/modules/widget/config/popularity/package-downloads/package-downloads.config.ts
- frontend/app/components/modules/widget/config/popularity/package-downloads/package-downloads.vue
- frontend/app/components/uikit/chart/helpers/chart-helpers.ts
- frontend/app/components/uikit/delta-display/delta-display.vue
- frontend/app/components/uikit/delta-display/types/delta-display.types.ts
- Hide empty columns for both the package downloads and dependency widgets
- Added "We don't have data before June 2025." to the description for both widgets
- Fix summary display for the dependency chart that overlaps for large values
[INS-732](https://linear.app/lfx/issue/INS-732/exclude-all-periods-before-june-2025-in-package-downloadsdependencies)
> feat: hide empty columns for package downloads and dependency charts

- frontend/server/api/project/[slug]/popularity/search-queries.get.ts
Added a sort function on the search queries endpoint to sort the data returned by startDate
[INS-734](https://linear.app/lfx/issue/INS-734/wrong-display-of-data-in-search-queries-volume-widget)
> fix: sorting of data returned by the search queries endpoint

- frontend/app/components/modules/project/components/overview/about-section/project-criticality.vue
- frontend/app/config/links.ts
Fixed the learn more link on the project criticality score widget
[INS-730](https://linear.app/lfx/issue/INS-730/fix-learn-more-link-in-criticality-score-card)
> fix: incorrect project criticality learn more link

- frontend/app/components/modules/widget/config/development/pull-requests/pull-requests.vue
- frontend/server/api/project/[slug]/overview/health-score.get.ts
- Changed the date parameter for the retention score in the overview health scores. 
- Changed the metric used for calculating the new pull request score. Before we were using the total pull request, it is now set to use the opened pull requests only
[INS-751](https://linear.app/lfx/issue/INS-751/benchmark-fixes) and all it's sub tickets
> fix: benchmark scores

- frontend/app/components/modules/project/services/security.service.ts
Added function that filters out the OSPS-AC-01 check on the security and best practices data. This removes it both from the UI and the score calculation
[INS-752](https://linear.app/lfx/issue/INS-752/hide-the-osps-ac-0101-mfa-on-insights)
> chore: removed the check for OSPS-AC-01

- frontend/app/components/modules/project/components/shared/header/repository-switch.vue
- frontend/app/components/uikit/modal/modal.vue
Fixed the height issue for the repository modal that causes 2 scroll bars when the user views the app in smaller screen sizes
[INS-735](https://linear.app/lfx/issue/INS-735/repositories-list-scroll-bar-messed-up-in-shorter-browser-window)
> fix: height bug repository modal

- frontend/app/components/modules/project/components/overview/trust-score.vue
Fix issue on the overview trust score component that causes the layout to be broken while loading. This was caused by the empty state message showing up.
NO TICKET
> fix: jumping layout issue on trust score when loading

- database/migrate.sh
I found myself in need of running Flyway commands other than `migrate`.
This change allows doing that with the `migrate.sh` script, while still defaulting to the `migrate` command to preserve the previous behaviour.
- `main` 
- \#512 :point\_left:
- \#513
> chore: allow running other commands in the migration script

- frontend/app/components/modules/project/views/overview.vue
- frontend/app/components/modules/widget/components/shared/widget-area.vue
- frontend/app/components/modules/widget/config/popularity/forks/forks.vue
- frontend/app/components/modules/widget/config/popularity/mailing-list-messages/mailing-list-messages.vue
- frontend/app/components/modules/widget/config/popularity/press-mentions/press-mentions.vue
- frontend/app/components/modules/widget/config/popularity/search-queries/search-queries.vue
- frontend/app/components/modules/widget/config/popularity/stars/stars.vue
- frontend/app/components/modules/widget/services/popularity.api.service.ts
- Refactored the data fetching for all the widgets under the popularity tab
- Added data calls in the widget area to popularity tab data to check if data is present for certain widgets
- Update the overview health score to hide the search queries score if it's empty
[INS-824](https://linear.app/lfx/issue/INS-824/hide-widgets-if-they-dont-have-value)
> chore: hide widgets without data

- frontend/app/components/modules/widget/config/popularity/stars/stars.config.ts
Fix minor typo on the GitHub name that appears in the benchmark scores
> fix: github name typo

- frontend/app/components/modules/project/components/shared/header.vue
- frontend/app/config/menu/index.ts
Change the UI implementation of report issue button on the project header.
[INS-843](https://linear.app/lfx/issue/INS-843/report-data-button-not-following-latest-design-update)
[INS-842](https://linear.app/lfx/issue/INS-842/update-documentation-menu-copy)
> fix: report issue button UI implementation

- frontend/app/components/modules/project/components/shared/header.vue
- frontend/app/components/modules/project/store/project.store.ts
- frontend/app/components/modules/project/views/overview.vue
- frontend/app/components/modules/project/views/security.vue
When selecting repositories in the search list and no archived repository is selected, the "includes archived repositories" tag is still being shown.
The condition to show the tag was checking just if the project itself contained archived repositories, not if there were archived repositories in the list of selected ones.
This also affects other places, like the security tab and the project overview, where the indication of archived repositories is also shown.
> fix: fix "includes archived repos" tag being shown when no archived repos are selected

- frontend/app/components/modules/project/components/shared/header.vue
- frontend/app/components/modules/project/components/shared/header/project-menu.vue
- frontend/app/components/modules/widget/components/shared/widget-area.vue
- Fix the project tab menus on mobile
- Adjust the project name and repository dropdown wrapping for different screen sizes
[IN-723](https://linuxfoundation.atlassian.net/browse/IN-723)
[IN-723]: https://linuxfoundation.atlassian.net/browse/IN-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: project header items and menu UI on mobile view

- frontend/docs/introduction/contributions/index.md
- Properly define "commit" activity types for all platforms.
- Make proper distinction between Git and GitHub/Gitlab (which branch the commits are being fetched from)
> docs: update authored commit definition

- frontend/app/components/shared/layout/banner.vue
- frontend/app/components/shared/layout/navbar.vue
- Breakout the banner to a separate component
- Implemented design improvement on the kubecon banner
[IN-716](https://linuxfoundation.atlassian.net/browse/IN-716)
[IN-716]: https://linuxfoundation.atlassian.net/browse/IN-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: kubecon banner improvements

- frontend/docs/introduction/contributions/index.md
Updated terminology in the contributions documentation to clarify the distinction between code contributions and collaborations.
> docs: clarify contributions vs code contributions terminology

- frontend/app/components/modules/widget/components/contributors/fragments/activities-dropdown.vue
- frontend/app/config/platforms/configs/confluence.platform.ts
- frontend/app/config/platforms/configs/discord.platform.ts
- frontend/app/config/platforms/configs/github.platform.ts
- frontend/app/config/platforms/configs/gitlab.platform.ts
- frontend/app/config/platforms/configs/groupsio.platform.ts
- frontend/app/config/platforms/configs/jira.platform.ts
- frontend/app/config/platforms/configs/slack.platform.ts
- frontend/app/config/platforms/configs/stackoverflow.platform.ts
- frontend/eslint.config.mjs
- frontend/types/shared/platforms.types.ts
- Added new flag to the activity types in the platform configs for the collaboration flag
- Used new flag in the activity types dropdown to filter out collaborations only types if the the include collaborations toggle is set to false
- Reset the selected activity type if the current one is not included in the activity types list when the user toggles the include collaborations back to false
[N-760](https://linuxfoundation.atlassian.net/browse/IN-760)
> feat: add dynamic activity type filtering when toggling collaborations
